# Generated by Django 6.0 on 2025-12-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blessings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userblessing',
            name='to_email',
        ),
    ]
